#spring.application.name=Lucete
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/lucete


    username: ohgiraffers
    password: ohgiraffers


    mail:
      host: smtp.naver.com
      port: 465
      username: mydogduri@naver.com
      password:
      properties:
        mail.smtp.auth: true
        mail.smtp.ssl.enable: true


  servlet:
    multipart:
      location: C:/Users/hi/Desktop/product-jan/Lucete
      max-file-size: 20MB
      max-request-size: 20MB
  web:
    resources:
      static-locations: /static/**

#mybats config
mybatis:
  mapper-locations: mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

# image upload dir
image:
  image-dir: C:/practice
